//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream chord {
            get {
                return ResourceManager.GetStream("chord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream notify {
            get {
                return ResourceManager.GetStream("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;D&quot;:[{&quot;end_station_name&quot;:&quot;&quot;,&quot;end_time&quot;:&quot;&quot;,&quot;id&quot;:&quot;4&quot;,&quot;start_station_name&quot;:&quot;&quot;,&quot;start_time&quot;:&quot;&quot;,&quot;value&quot;:&quot;软卧&quot;},{&quot;end_station_name&quot;:&quot;&quot;,&quot;end_time&quot;:&quot;&quot;,&quot;id&quot;:&quot;6&quot;,&quot;start_station_name&quot;:&quot;&quot;,&quot;start_time&quot;:&quot;&quot;,&quot;value&quot;:&quot;高级软卧&quot;},{&quot;end_station_name&quot;:&quot;&quot;,&quot;end_time&quot;:&quot;&quot;,&quot;id&quot;:&quot;9&quot;,&quot;start_station_name&quot;:&quot;&quot;,&quot;start_time&quot;:&quot;&quot;,&quot;value&quot;:&quot;商务座&quot;},{&quot;end_station_name&quot;:&quot;&quot;,&quot;end_time&quot;:&quot;&quot;,&quot;id&quot;:&quot;M&quot;,&quot;start_station_name&quot;:&quot;&quot;,&quot;start_time&quot;:&quot;&quot;,&quot;value&quot;:&quot;一等座&quot;},{&quot;end_station_name&quot;:&quot;&quot;,&quot;end_time&quot;:&quot;&quot;,&quot;id&quot;:&quot;O&quot;,&quot;start_sta... 的本地化字符串。
        /// </summary>
        internal static string SeatTypeRelation {
            get {
                return ResourceManager.GetString("SeatTypeRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] srca {
            get {
                object obj = ResourceManager.GetObject("srca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 @bjb|北京北|VAP|beijingbei|bjb|0@bjd|北京东|BOP|beijingdong|bjd|1@bji|北京|BJP|beijing|bj|2@bjn|北京南|VNP|beijingnan|bjn|3@bjx|北京西|BXP|beijingxi|bjx|4@cqb|重庆北|CUW|chongqingbei|cqb|5@cqi|重庆|CQW|chongqing|cq|6@cqn|重庆南|CRW|chongqingnan|cqn|7@sha|上海|SHH|shanghai|sh|8@shn|上海南|SNH|shanghainan|shn|9@shq|上海虹桥|AOH|shanghaihongqiao|shhq|10@shx|上海西|SXH|shanghaixi|shx|11@tjb|天津北|TBP|tianjinbei|tjb|12@tji|天津|TJP|tianjin|tj|13@tjn|天津南|TIP|tianjinnan|tjn|14@tjx|天津西|TXP|tianjinxi|tjx|15@cch|长春|CCT|changchun|cc|16@ccn|长春南|CET|changch [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StationNames {
            get {
                return ResourceManager.GetString("StationNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 body{margin:0px; background:#666666; overflow:auto}
        ///.table_list{ margin-bottom:10px; font-size:12px; background:#9EB6CE;}
        ///.table_list th{ font-size:14px; font-weight:bold; color:#155BA3; text-align:left; padding-left:18px; height:34px; background:url(../images/table_th_bg.jpg) repeat-x top;}
        ///.table_list td{ background:#fff; height:20px; padding-left:5px; line-height:20px;}
        ///.table_th2 td{ background:#E8F0F9; padding-left:5px; color:#155BA3; font-weight:bold;line-height:25px;}
        ///.table_th3 td{ background:# [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
    }
}
